/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CardHandler.Card;
import CardHandler.CardHandler;
import CombinedPattern.TemplateDesignPattern.EngageTransaction;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Image;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Luchn1k
 */
public class ATM extends javax.swing.JFrame {

    /**
     * Creates new form ATM
     */
    Card currentCard;
    CardHandler cardHandler;
    private final CardLayout CARD_LAYOUT;
    private boolean isPasswordTypable;
    private boolean isAmmountTypable;
    private double ammount;
    private String currentLayout = "welcome";

    public ATM() {
        initComponents();
        cardHandler = cardHandler.getInstance();
        genarateCards();
        display.add(welcomePanel, "welcome");
        display.add(passwordPanel, "password");
        display.add(optionWindow, "mainMenu");
        display.add(checkMoneyPnl, "checkMoney");
        display.add(ReciptPrint, "receipt");
        display.add(endPnl, "end");
        display.add(withdrawMoneyAmmount, "withdrawAmmount");
        CARD_LAYOUT = (CardLayout) (display.getLayout());

        CARD_LAYOUT.show(display, "welcome");

        ImageIcon imageIcon = new ImageIcon(new ImageIcon("src/Images/insert-card.gif").getImage().getScaledInstance(128, 128, Image.SCALE_DEFAULT));
        cardInsertAnimation.setIcon(imageIcon);

    }

    Dimension getScaledDimension(Dimension imageSize, Dimension boundary) {

        double widthRatio = boundary.getWidth() / imageSize.getWidth();
        double heightRatio = boundary.getHeight() / imageSize.getHeight();
        double ratio = Math.min(widthRatio, heightRatio);
        return new Dimension((int) (imageSize.width * ratio),
                (int) (imageSize.height * ratio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        display = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cardInsertAnimation = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        optionWindow = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        checkMoneyPnl = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cardHolderNameTxt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        avilableMoneyTxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cardNumberView = new javax.swing.JLabel();
        withdrawMoneyAmmount = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ammountTxt = new javax.swing.JTextField();
        ReciptPrint = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        endPnl = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnPnl = new javax.swing.JPanel();
        nineBtn = new javax.swing.JButton();
        eightBtn = new javax.swing.JButton();
        sevenBtn = new javax.swing.JButton();
        foutBtn = new javax.swing.JButton();
        fiveBtn = new javax.swing.JButton();
        sixBtn = new javax.swing.JButton();
        oneBtn = new javax.swing.JButton();
        twoBtn = new javax.swing.JButton();
        threeBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        enterBtn = new javax.swing.JButton();
        zeroBtn = new javax.swing.JButton();
        enterBtn1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cardNumber = new javax.swing.JTextField();
        cardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABC ATM");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ABC Bank");

        display.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        display.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome To ABC Bank ");

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Insert Your Card To Continue");

        cardInsertAnimation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cardInsertAnimation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/insert-card.gif"))); // NOI18N

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardInsertAnimation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardInsertAnimation, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        display.add(welcomePanel, "card2");

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Insert Your Password");

        passwordTxt.setEditable(false);
        passwordTxt.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        passwordTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordTxtKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordTxt)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        display.add(passwordPanel, "card3");

        jButton1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton1.setText("Check Balance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jButton2.setText("Withdraw Money");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionWindowLayout = new javax.swing.GroupLayout(optionWindow);
        optionWindow.setLayout(optionWindowLayout);
        optionWindowLayout.setHorizontalGroup(
            optionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );
        optionWindowLayout.setVerticalGroup(
            optionWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionWindowLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        display.add(optionWindow, "card4");

        jLabel6.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Card Holdr Name :");

        cardHolderNameTxt.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        cardHolderNameTxt.setForeground(new java.awt.Color(255, 255, 102));
        cardHolderNameTxt.setText("Pasindu Kalana Maduranga");

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Avilable Money :");

        avilableMoneyTxt.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        avilableMoneyTxt.setForeground(new java.awt.Color(255, 255, 102));
        avilableMoneyTxt.setText("Rs. 0");

        jLabel12.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText("Account Number :");

        cardNumberView.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        cardNumberView.setForeground(new java.awt.Color(255, 255, 102));
        cardNumberView.setText("7787878784545");

        javax.swing.GroupLayout checkMoneyPnlLayout = new javax.swing.GroupLayout(checkMoneyPnl);
        checkMoneyPnl.setLayout(checkMoneyPnlLayout);
        checkMoneyPnlLayout.setHorizontalGroup(
            checkMoneyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkMoneyPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(checkMoneyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardHolderNameTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avilableMoneyTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardNumberView, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );
        checkMoneyPnlLayout.setVerticalGroup(
            checkMoneyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkMoneyPnlLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardHolderNameTxt)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cardNumberView)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avilableMoneyTxt)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        display.add(checkMoneyPnl, "card5");

        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("Enter The Ammount");

        ammountTxt.setEditable(false);
        ammountTxt.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N

        javax.swing.GroupLayout withdrawMoneyAmmountLayout = new javax.swing.GroupLayout(withdrawMoneyAmmount);
        withdrawMoneyAmmount.setLayout(withdrawMoneyAmmountLayout);
        withdrawMoneyAmmountLayout.setHorizontalGroup(
            withdrawMoneyAmmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMoneyAmmountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(withdrawMoneyAmmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addComponent(ammountTxt))
                .addContainerGap())
        );
        withdrawMoneyAmmountLayout.setVerticalGroup(
            withdrawMoneyAmmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMoneyAmmountLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addGap(32, 32, 32)
                .addComponent(ammountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        display.add(withdrawMoneyAmmount, "card6");

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Do You Need a receipt for this transaction ?");

        jButton3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("NO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 204, 0));
        jButton4.setText("YES");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ReciptPrintLayout = new javax.swing.GroupLayout(ReciptPrint);
        ReciptPrint.setLayout(ReciptPrintLayout);
        ReciptPrintLayout.setHorizontalGroup(
            ReciptPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReciptPrintLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ReciptPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReciptPrintLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ReciptPrintLayout.setVerticalGroup(
            ReciptPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReciptPrintLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(ReciptPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        display.add(ReciptPrint, "card7");

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Thank You !");

        jLabel11.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 102));
        jLabel11.setText("Please Collect the mony and Card");

        javax.swing.GroupLayout endPnlLayout = new javax.swing.GroupLayout(endPnl);
        endPnl.setLayout(endPnlLayout);
        endPnlLayout.setHorizontalGroup(
            endPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(endPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );
        endPnlLayout.setVerticalGroup(
            endPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(endPnlLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addGap(53, 53, 53)
                .addComponent(jLabel11)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        display.add(endPnl, "card8");

        btnPnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nineBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        nineBtn.setText("9");
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });

        eightBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        eightBtn.setText("8");
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });

        sevenBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        sevenBtn.setText("7");
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });

        foutBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        foutBtn.setText("4");
        foutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foutBtnActionPerformed(evt);
            }
        });

        fiveBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        fiveBtn.setText("5");
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });

        sixBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        sixBtn.setText("6");
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });

        oneBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        oneBtn.setText("1");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });

        twoBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        twoBtn.setText("2");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });

        threeBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        threeBtn.setText("3");
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        enterBtn.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        enterBtn.setText("Enter");
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });

        zeroBtn.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        zeroBtn.setText("0");
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });

        enterBtn1.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        enterBtn1.setText("Back");
        enterBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPnlLayout = new javax.swing.GroupLayout(btnPnl);
        btnPnl.setLayout(btnPnlLayout);
        btnPnlLayout.setHorizontalGroup(
            btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btnPnlLayout.createSequentialGroup()
                        .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnPnlLayout.createSequentialGroup()
                        .addComponent(foutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(btnPnlLayout.createSequentialGroup()
                        .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(btnPnlLayout.createSequentialGroup()
                                .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        btnPnlLayout.setVerticalGroup(
            btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnPnlLayout.createSequentialGroup()
                        .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eightBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sevenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(foutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sixBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(btnPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zeroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel4.setText("Card Number");

        cardNumber.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N

        cardBtn.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        cardBtn.setText("Insert");
        cardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        String btnValue = fiveBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void cardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardBtnActionPerformed
        if (cardBtn.getText().equals("Insert")) {
            String cardNumberTxt = cardNumber.getText().trim();
            if (cardHandler.isValidCardNumber(cardNumberTxt)) {
                currentCard = cardHandler.getCard(cardNumberTxt);
                currentLayout = "password";
                CARD_LAYOUT.show(display, "password");
                cardNumber.setEditable(false);
                cardBtn.setEnabled(false);
                isPasswordTypable = true;

            }
        } else if (cardBtn.getText().equals("Collect")) {
            cardNumber.setText(null);
            cardNumber.setEditable(true);
            cardBtn.setText("Insert");
            currentLayout = "welcome";
            CARD_LAYOUT.show(display, "welcome");
        }

    }//GEN-LAST:event_cardBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        String btnValue = nineBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_nineBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        String btnValue = eightBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_eightBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        String btnValue = sevenBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void foutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foutBtnActionPerformed
        String btnValue = foutBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_foutBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        String btnValue = sixBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_sixBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        String btnValue = oneBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        String btnValue = twoBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        String btnValue = threeBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_threeBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        String btnValue = zeroBtn.getText().trim();
        if (isPasswordTypable && !isAmmountTypable) {
            if (passwordTxt.getText().trim().length() != 4) {
                passwordTxt.setText(passwordTxt.getText() + btnValue);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            ammountTxt.setText(ammountTxt.getText() + btnValue);
        }
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void passwordTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyTyped

    }//GEN-LAST:event_passwordTxtKeyTyped

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        if (isPasswordTypable && !isAmmountTypable) {
            String password = passwordTxt.getText().trim();
            if (password.length() >= 1) {
                String substring = password.substring(0, password.length() - 1);
                passwordTxt.setText(substring);
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            String ammount = ammountTxt.getText().trim();
            if (ammount.length() >= 1) {
                String substring = ammount.substring(0, ammount.length() - 1);
                ammountTxt.setText(substring);
            }
        }
    }//GEN-LAST:event_clearBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        currentLayout = "welcome";
        CARD_LAYOUT.show(display, "welcome");
        cardNumber.setText("");
        cardNumber.setEditable(true);
        cardBtn.setEnabled(true);
        isPasswordTypable = true;
        isAmmountTypable = false;

    }//GEN-LAST:event_cancelBtnActionPerformed

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        if (isPasswordTypable && !isAmmountTypable) {
            if (currentCard.getCardPassword().equals(passwordTxt.getText().trim())) {
                currentLayout = "mainMenu";
                CARD_LAYOUT.show(display, "mainMenu");
                passwordTxt.setText(null);
            } else {
                message("Invalid Password. Check your card pin number", "Error");
            }
        } else if (isAmmountTypable && !isPasswordTypable) {
            int ammount = Integer.parseInt(ammountTxt.getText().trim());
            if (ammount > 0) {
                this.ammount = ammount;
                currentLayout = "receipt";
                CARD_LAYOUT.show(display, "receipt");
            } else {
                message("Ammount Must be larger than 0", "Error");
            }
        }

    }//GEN-LAST:event_enterBtnActionPerformed
    private void message(String message, String title) {
        boolean defaultLFDecorated = JDialog.isDefaultLookAndFeelDecorated();
        try {
            JDialog.setDefaultLookAndFeelDecorated(true);
            JOptionPane pane = new JOptionPane(message, JOptionPane.ERROR_MESSAGE, JOptionPane.DEFAULT_OPTION);
            JDialog dialog = pane.createDialog(display, title);
            dialog.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
            pane.setOpaque(false);
            ArrayList<Component> components = new ArrayList<Component>(Arrays.asList(pane.getComponents()));
            while (!components.isEmpty()) {
                Component c = components.remove(0);
                if (c instanceof JComponent) {
                    ((JComponent) c).setOpaque(false);
                }

                if (c instanceof Container) {
                    components.addAll(Arrays.asList(((Container) c).getComponents()));
                }
            }

            dialog.setVisible(true);
            dialog.dispose();
        } finally {
            JDialog.setDefaultLookAndFeelDecorated(defaultLFDecorated);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        currentLayout = "checkMoney";
        CARD_LAYOUT.show(display, "checkMoney");
        NumberFormat formatter = new DecimalFormat("#.##");
        cardHolderNameTxt.setText(currentCard.getCardHolder());
        avilableMoneyTxt.setText("Rs. " + formatter.format(currentCard.getAvilableMoney()));
        cardNumberView.setText(currentCard.getCardNumber());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        currentLayout = "withdrawAmmount";
        CARD_LAYOUT.show(display, "withdrawAmmount");
        isPasswordTypable = false;
        isAmmountTypable = true;

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        EngageTransaction transaction = new EngageTransaction(currentCard, ammount);
        boolean proceed = transaction.proceed(false);
        if (proceed) {
            endTransaction(true);
        } else {
            message("Something is invalid. Contact Your Bank", "Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        EngageTransaction transaction = new EngageTransaction(currentCard, ammount);
        boolean proceed = transaction.proceed(true);
        if (proceed) {
            endTransaction(true);
        } else {
            message("Something is invalid. Contact Your Bank", "Error");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void enterBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtn1ActionPerformed
        ammount = 0;
        if ("checkMoney".equals(currentLayout)) {
            currentLayout = "mainMenu";
            ammountTxt.setText(null);
        } else if ("withdrawAmmount".equals(currentLayout)) {
            currentLayout = "mainMenu";
            ammountTxt.setText(null);
        } else if ("receipt".equals(currentLayout)) {
            currentLayout = "withdrawAmmount";
        }

        CARD_LAYOUT.show(display, currentLayout);

    }//GEN-LAST:event_enterBtn1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      ImageIcon icon = new ImageIcon("src/images/ico.png");
        setIconImage(icon.getImage());
    }//GEN-LAST:event_formWindowOpened
    private void endTransaction(boolean recipt) {
        currentLayout = "end";
        CARD_LAYOUT.show(display, "end");
        isPasswordTypable = false;
        isAmmountTypable = false;
        cardBtn.setEnabled(true);
        cardBtn.setText("Collect");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatDarkLaf.setup();
                try {
                    UIManager.setLookAndFeel(new FlatDarkPurpleIJTheme());
                    UIManager.put("Button.arc", 999);
                    UIManager.put("Component.arc", 999);
                    UIManager.put("ProgressBar.arc", 999);
                    UIManager.put("TextComponent.arc", 999);
                } catch (UnsupportedLookAndFeelException ex) {
                    System.err.println("Failed to initialize LaF");
                }
                new ATM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ReciptPrint;
    private javax.swing.JTextField ammountTxt;
    private javax.swing.JLabel avilableMoneyTxt;
    private javax.swing.JPanel btnPnl;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cardBtn;
    private javax.swing.JLabel cardHolderNameTxt;
    private javax.swing.JLabel cardInsertAnimation;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JLabel cardNumberView;
    private javax.swing.JPanel checkMoneyPnl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JPanel display;
    private javax.swing.JButton eightBtn;
    private javax.swing.JPanel endPnl;
    private javax.swing.JButton enterBtn;
    private javax.swing.JButton enterBtn1;
    private javax.swing.JButton fiveBtn;
    private javax.swing.JButton foutBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nineBtn;
    private javax.swing.JButton oneBtn;
    private javax.swing.JPanel optionWindow;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JButton sevenBtn;
    private javax.swing.JButton sixBtn;
    private javax.swing.JButton threeBtn;
    private javax.swing.JButton twoBtn;
    private javax.swing.JPanel welcomePanel;
    private javax.swing.JPanel withdrawMoneyAmmount;
    private javax.swing.JButton zeroBtn;
    // End of variables declaration//GEN-END:variables

    private void genarateCards() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            Card card1 = new Card("4250426132627726", "Delfina Chika Zamorano", "8957", sdf.parse("2023-01-31"), "commercial bank", 45000);
            Card card2 = new Card("4607831933690056", "Faustinus Claus Allard", "6492", sdf.parse("2023-03-23"), "peoples bank", 8520777);
            Card card3 = new Card("4897289065871052", "Alycia Seppo Fylan", "3445", sdf.parse("2023-04-03"), "hatton national bank", 56895280);
            Card card4 = new Card("5215436541657280", "Gabriele Carmela Adriatico", "3144", sdf.parse("2023-05-17"), "sampath bank", 70000);
            Card card5 = new Card("4748559183741903", "Camilla Priidik Falk", "9120", sdf.parse("2023-10-27"), "seylan bank", 400);

            cardHandler.addCard(card1);
            cardHandler.addCard(card2);
            cardHandler.addCard(card3);
            cardHandler.addCard(card4);
            cardHandler.addCard(card5);

        } catch (ParseException ex) {
            Logger.getLogger(ATM.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
}
