/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Memento.HitLocation;
import com.formdev.flatlaf.FlatDarkLaf;
import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.CardLayout;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.io.File;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Luchn1k
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    ImageIcon targetImage = new ImageIcon("src/Images/bullseye.png");
    ImageIcon shotImage = new ImageIcon("src/Images/hole.png");
    int clickCount;
    int hitCount;
    boolean isClicable;
    private final int COUNTDOWN = 5;
    private final String COUNTDOWNTEXT = "Game stats in ";
    Thread gameThread;

    private CardLayout cardlayout;

    Image customimageAim = new ImageIcon("src/Images/customCursor.png").getImage();
    Image customimageNone = new ImageIcon("src/Images/none.png").getImage();
    Cursor customCursorAim = Toolkit.getDefaultToolkit().createCustomCursor(customimageAim, new Point(16, 16), "customCursor");
    Cursor customCursorNone = Toolkit.getDefaultToolkit().createCustomCursor(customimageNone, new Point(16, 16), "customCursor");
    HitLocation hitLocation;
    String path = "src/Audio/sound.wav";
    AudioClip newAudioClip;

    private Rectangle currenTargetLocation;
    private Rectangle currentClickLocation;

    private final String GAME = "gameScreen";
    private final String SETTINGS = "settings";
    private final String HOME = "home";

    public Game() {
        initComponents();

        CardParent.add(homePanel, HOME);
        CardParent.add(settingsPnl, SETTINGS);
        CardParent.add(gameCardPnl, GAME);
        cardlayout = (CardLayout) (CardParent.getLayout());

        target.setIcon(targetImage);
        shot.setIcon(shotImage);
        shot.hide();
        target.hide();
        target.setCursor(customCursorNone);
        gameStartLbl.setVisible(false);
        summeryPnl.setVisible(false);

        try {
            newAudioClip = Applet.newAudioClip(new File(path).toURL());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void randomTargetGenarator() {
        target.show();
        int x = (int) (Math.random() * (gamePnl.getWidth() - 70));
        int y = (int) (Math.random() * (gamePnl.getHeight() - 70));
        target.setBounds(x, y, 64, 64);

    }

    private void setShot(int clickX, int clickY) {
        if (isClicable) {
            newAudioClip.play();
            shot.show();
            shot.setBounds(clickX - 16, clickY - 16, 32, 32);
            currenTargetLocation = target.getBounds();
            currentClickLocation = shot.getBounds();
            clickCount++;
            if (hitLocation == null) {
                hitLocation = new HitLocation(currentClickLocation, currenTargetLocation);
            }
            hitLocation.setHitLocation(currentClickLocation);
            hitLocation.setTargetLocation(currenTargetLocation);
            hitLocation.save();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardParent = new javax.swing.JPanel();
        settingsPnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        targetCountTxt = new javax.swing.JTextField();
        targetSpeedTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        PnlColor = new javax.swing.JColorChooser();
        jButton1 = new javax.swing.JButton();
        gameCardPnl = new javax.swing.JPanel();
        gamePnl = new javax.swing.JPanel();
        shot = new javax.swing.JLabel();
        target = new javax.swing.JLabel();
        summeryPnl = new javax.swing.JPanel();
        countDataLbl = new javax.swing.JLabel();
        accuracyDataTxt = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        gameStartLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        playAgainBtn = new javax.swing.JButton();
        mainMenuBtn = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.CardLayout());

        CardParent.setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel3.setText("Enter Your Target count");

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel4.setText("Enter Your Target Speed");

        targetCountTxt.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        targetCountTxt.setText("10");

        targetSpeedTxt.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        targetSpeedTxt.setText("1000");
        targetSpeedTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetSpeedTxtActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel5.setText("ms");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(targetSpeedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(targetCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(targetCountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(targetSpeedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(49, 49, 49))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Backgroud Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        PnlColor.setColor(new java.awt.Color(51, 51, 55));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PnlColor, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnlColor, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout settingsPnlLayout = new javax.swing.GroupLayout(settingsPnl);
        settingsPnl.setLayout(settingsPnlLayout);
        settingsPnlLayout.setHorizontalGroup(
            settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPnlLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        settingsPnlLayout.setVerticalGroup(
            settingsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsPnlLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        CardParent.add(settingsPnl, "card3");

        gamePnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gamePnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gamePnlMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gamePnlMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gamePnlMouseReleased(evt);
            }
        });
        gamePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hole.png"))); // NOI18N
        gamePnl.add(shot, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 32, 32));

        target.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        target.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bullseye.png"))); // NOI18N
        target.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                targetMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                targetMouseReleased(evt);
            }
        });
        gamePnl.add(target, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 64, 64));

        summeryPnl.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Summery", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        countDataLbl.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        countDataLbl.setText("Shots");

        accuracyDataTxt.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        accuracyDataTxt.setText("Accuracy");

        jButton2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jButton2.setText("History");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout summeryPnlLayout = new javax.swing.GroupLayout(summeryPnl);
        summeryPnl.setLayout(summeryPnlLayout);
        summeryPnlLayout.setHorizontalGroup(
            summeryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summeryPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(summeryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countDataLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accuracyDataTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                .addContainerGap())
        );
        summeryPnlLayout.setVerticalGroup(
            summeryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summeryPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(countDataLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accuracyDataTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        gameStartLbl.setFont(new java.awt.Font("Elephant", 1, 20)); // NOI18N
        gameStartLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameStartLbl.setText("Game Starts In");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controls", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DialogInput", 1, 14))); // NOI18N

        playAgainBtn.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        playAgainBtn.setText("Play Again");
        playAgainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainBtnActionPerformed(evt);
            }
        });

        mainMenuBtn.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        mainMenuBtn.setText("Main Menu");
        mainMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playAgainBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainMenuBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(playAgainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainMenuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gameCardPnlLayout = new javax.swing.GroupLayout(gameCardPnl);
        gameCardPnl.setLayout(gameCardPnlLayout);
        gameCardPnlLayout.setHorizontalGroup(
            gameCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameCardPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gamePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 1301, Short.MAX_VALUE)
                    .addGroup(gameCardPnlLayout.createSequentialGroup()
                        .addComponent(gameStartLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(summeryPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        gameCardPnlLayout.setVerticalGroup(
            gameCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameCardPnlLayout.createSequentialGroup()
                .addGroup(gameCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameCardPnlLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(gameStartLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameCardPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(gameCardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(summeryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gamePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        CardParent.add(gameCardPnl, "card4");

        jLabel1.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homeImage.png"))); // NOI18N
        jLabel1.setText("Prototype Aim Trainer");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        playButton.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        playButton.setText("Play");
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jButton4.setText("Settings");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jButton5.setText("Quit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(playButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(400, 400, 400))
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(91, 91, 91)
                .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        CardParent.add(homePanel, "card2");

        getContentPane().add(CardParent, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gamePnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamePnlMouseClicked

    }//GEN-LAST:event_gamePnlMouseClicked

    private void targetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_targetMouseClicked

    }//GEN-LAST:event_targetMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.pack();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void gamePnlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamePnlMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1) {
            setShot(evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_gamePnlMouseReleased

    private void targetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_targetMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON1) {
            hitCount++;
            setShot(target.getX() + evt.getX(), target.getY() + evt.getY());
        }
    }//GEN-LAST:event_targetMouseReleased

    private void gamePnlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamePnlMousePressed

    }//GEN-LAST:event_gamePnlMousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hitLocation.undo();
        if (hitLocation != null) {
            if (shot != null) {
                target.show();
                shot.show();
                target.setBounds(hitLocation.getTargetLocation());
                shot.setBounds(hitLocation.getHitLocation());
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed

        cardlayout.show(CardParent, GAME);
        startGame();

    }//GEN-LAST:event_playButtonActionPerformed
    private void startGame() {
        hitLocation = null;
        if (PnlColor.getColor() != null) {
            gamePnl.setBackground(PnlColor.getColor());
        }
        shot.hide();
        target.hide();
        if (gameThread != null) {
            if (gameThread.isAlive()) {
                gameThread.stop();
                reset();

            }
        }
        summeryPnl.setVisible(false);
        int targetCount = Integer.parseInt(targetCountTxt.getText().trim());
        int targetSpeed = Integer.parseInt(targetSpeedTxt.getText().trim());

        gameThread = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = COUNTDOWN; i >= 0; i--) {
                    gameStartLbl.setText(COUNTDOWNTEXT + i + "...");
                    gameStartLbl.setVisible(true);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                gameStartLbl.setVisible(false);
                target.setCursor(customCursorAim);
                gamePnl.setCursor(customCursorAim);
                isClicable = true;
                for (int i = 0; i < targetCount; i++) {
                    randomTargetGenarator();
                    try {
                        Thread.sleep(targetSpeed);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                summeryPnl.setVisible(true);
                countDataLbl.setText("You Hit " + hitCount + " out of " + targetCount + " by using " + clickCount + " Shots");
                DecimalFormat df = new DecimalFormat("##.##");
                accuracyDataTxt.setText("Your Accuracy is  " + df.format(calculateAcuracy(targetCount)) + "%");
                reset();
            }
        });
        gameThread.start();
    }
    private void targetSpeedTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetSpeedTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_targetSpeedTxtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void playAgainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainBtnActionPerformed
        startGame();
    }//GEN-LAST:event_playAgainBtnActionPerformed

    private void mainMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuBtnActionPerformed
        cardlayout.show(CardParent, HOME);
    }//GEN-LAST:event_mainMenuBtnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cardlayout.show(CardParent, SETTINGS);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cardlayout.show(CardParent, HOME);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void reset() {
        target.hide();
        shot.hide();
        clickCount = 0;
        hitCount = 0;
        isClicable = false;
        target.setCursor(customCursorNone);
        gamePnl.setCursor(customCursorNone);
    }

    private double calculateAcuracy(int targetCount) {
        int originalClicks = clickCount > targetCount ? clickCount : targetCount;
        return ((Double.valueOf(hitCount) / Double.valueOf(originalClicks)) * Double.valueOf(100));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FlatDarkLaf.setup();
                try {
                    UIManager.setLookAndFeel(new FlatDarkLaf());
                } catch (UnsupportedLookAndFeelException ex) {
                    System.err.println("Failed to initialize LaF");
                }
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardParent;
    private javax.swing.JColorChooser PnlColor;
    private javax.swing.JLabel accuracyDataTxt;
    private javax.swing.JLabel countDataLbl;
    private javax.swing.JPanel gameCardPnl;
    private javax.swing.JPanel gamePnl;
    private javax.swing.JLabel gameStartLbl;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton mainMenuBtn;
    private javax.swing.JButton playAgainBtn;
    private javax.swing.JButton playButton;
    private javax.swing.JPanel settingsPnl;
    private javax.swing.JLabel shot;
    private javax.swing.JPanel summeryPnl;
    private javax.swing.JLabel target;
    private javax.swing.JTextField targetCountTxt;
    private javax.swing.JTextField targetSpeedTxt;
    // End of variables declaration//GEN-END:variables
}
